package kbdmatrix
import java.util.ArrayList

class key(val s_code: String, val s_key: String, val s_modif: String) {
	def this(s_code: String, s_key: String) = this(s_code, s_key, "")

			override def toString(): String = s_key
			def toString1Char(): String = {
					if(s_key.indexOf("'dblquot")==0) {
						"'"
					} else if(s_key=="Space") {
						" "
					} else {
						s_key
					}
			}
			def getHex(): String = {
					s_code match {
					case KeyDoc.MatchHex(hexcode) => "0x"+hexcode
					case _ => ""
					}
			}
}

object KeyDoc {
	val MatchHex = """[^0]*0x(\p{XDigit}+).*""".r
			val i_maxWHQL = 127
			val m_keyref = Map(
					0  -> new key("(kbdm_NO_KEY              )","empty"),
					1  -> new key("(kbdm_PAGE_STD     + 0x035)","~"),
					2  -> new key("(kbdm_PAGE_STD     + 0x01E)","1!"),
					3  -> new key("(kbdm_PAGE_STD     + 0x01F)","2@"),
					4  -> new key("(kbdm_PAGE_STD     + 0x020)","3/"),
					5  -> new key("(kbdm_PAGE_STD     + 0x021)","4$"),
					6  -> new key("(kbdm_PAGE_STD     + 0x022)","5%"),
					7  -> new key("(kbdm_PAGE_STD     + 0x023)","6^"),
					8  -> new key("(kbdm_PAGE_STD     + 0x024)","7&"),
					9  -> new key("(kbdm_PAGE_STD     + 0x025)","8*"),
					10 -> new key("(kbdm_PAGE_STD     + 0x026)","9("),
					11 -> new key("(kbdm_PAGE_STD     + 0x027)","0)"),
					12 -> new key("(kbdm_PAGE_STD     + 0x02D)","-_"),
					13 -> new key("(kbdm_PAGE_STD     + 0x02E)","=+"),
					14 -> new key("(kbdm_PAGE_STD     + 0x089)","¥|"),
					15 -> new key("(kbdm_PAGE_STD     + 0x02A)","Bkspace"),
					16 -> new key("(kbdm_PAGE_STD     + 0x02B)","Tab"),
					17 -> new key("(kbdm_PAGE_STD     + 0x014)","Q"),
					18 -> new key("(kbdm_PAGE_STD     + 0x01A)","W"),
					19 -> new key("(kbdm_PAGE_STD     + 0x008)","E"),
					20 -> new key("(kbdm_PAGE_STD     + 0x015)","R"),
					21 -> new key("(kbdm_PAGE_STD     + 0x017)","T"),
					22 -> new key("(kbdm_PAGE_STD     + 0x01C)","Y"),
					23 -> new key("(kbdm_PAGE_STD     + 0x018)","U"),
					24 -> new key("(kbdm_PAGE_STD     + 0x00C)","I"),
					25 -> new key("(kbdm_PAGE_STD     + 0x012)","O"),
					26 -> new key("(kbdm_PAGE_STD     + 0x013)","P"),
					27 -> new key("(kbdm_PAGE_STD     + 0x02F)","[{"),
					28 -> new key("(kbdm_PAGE_STD     + 0x030)","]}"),
					29 -> new key("(kbdm_PAGE_STD     + 0x031)","Bkslash|"),
					30 -> new key("(kbdm_PAGE_STD     + 0x039)","CapsLck"),
					31 -> new key("(kbdm_PAGE_STD     + 0x004)","A"),
					32 -> new key("(kbdm_PAGE_STD     + 0x016)","S"),
					33 -> new key("(kbdm_PAGE_STD     + 0x007)","D"),
					34 -> new key("(kbdm_PAGE_STD     + 0x009)","F"),
					35 -> new key("(kbdm_PAGE_STD     + 0x00A)","G"),
					36 -> new key("(kbdm_PAGE_STD     + 0x00B)","H"),
					37 -> new key("(kbdm_PAGE_STD     + 0x00D)","J"),
					38 -> new key("(kbdm_PAGE_STD     + 0x00E)","K"),
					39 -> new key("(kbdm_PAGE_STD     + 0x00F)","L"),
					40 -> new key("(kbdm_PAGE_STD     + 0x033)",";:"),
					41 -> new key("(kbdm_PAGE_STD     + 0x034)","'dblquot"),
					42 -> new key("(kbdm_PAGE_STD     + 0x032)","$£"),
					43 -> new key("(kbdm_PAGE_STD     + 0x028)","Enter"),
					44 -> new key("(kbdm_PAGE_MOD     + 0x002)","L-Shift"),
					45 -> new key("(kbdm_PAGE_STD     + 0x064)","&lt;>"),
					46 -> new key("(kbdm_PAGE_STD     + 0x01D)","Z"),
					47 -> new key("(kbdm_PAGE_STD     + 0x01B)","X"),
					48 -> new key("(kbdm_PAGE_STD     + 0x006)","C"),
					49 -> new key("(kbdm_PAGE_STD     + 0x019)","V"),
					50 -> new key("(kbdm_PAGE_STD     + 0x005)","B"),
					51 -> new key("(kbdm_PAGE_STD     + 0x011)","N"),
					52 -> new key("(kbdm_PAGE_STD     + 0x010)","M"),
					53 -> new key("(kbdm_PAGE_STD     + 0x036)",",&lt;"),
					54 -> new key("(kbdm_PAGE_STD     + 0x037)",".>"),
					55 -> new key("(kbdm_PAGE_STD     + 0x038)","/ ?"),
					56 -> new key("(kbdm_PAGE_STD     + 0x087)","Ro"),
					57 -> new key("(kbdm_PAGE_MOD     + 0x020)","R-Shift"),
					58 -> new key("(kbdm_PAGE_MOD     + 0x001)","L-Ctrl"),
					59 -> new key("(kbdm_PAGE_MOD     + 0x008)","L-GUI"),
					60 -> new key("(kbdm_PAGE_MOD     + 0x004)","L-Alt"),
					61 -> new key("(kbdm_PAGE_STD     + 0x02C)","Space"),
					62 -> new key("(kbdm_PAGE_STD     + 0x0E6)","R-Alt"),
					63 -> new key("(kbdm_PAGE_STD     + 0x0XX)","R-GUI"),
					64 -> new key("(kbdm_PAGE_STD     + 0x0E4)","R-Ctrl"),
					75 -> new key("(kbdm_PAGE_STD     + 0x049)","Insert"),
					76 -> new key("(kbdm_PAGE_STD     + 0x04C)","Delete"),
					79 -> new key("(kbdm_PAGE_STD     + 0x050)","L-Arrow"),
					80 -> new key("(kbdm_PAGE_STD     + 0x04A)","Home"),
					81 -> new key("(kbdm_PAGE_STD     + 0x04D)","End"),
					83 -> new key("(kbdm_PAGE_STD     + 0x052)","UpArrow"),
					84 -> new key("(kbdm_PAGE_STD     + 0x051)","DnArrow"),
					85 -> new key("(kbdm_PAGE_STD     + 0x04B)","PageUp"),
					86 -> new key("(kbdm_PAGE_STD     + 0x04E)","PageDn"),
					89 -> new key("(kbdm_PAGE_STD     + 0x04F)","R-Arrow"),
					90 -> new key("(kbdm_PAGE_STD     + 0x053)","NumLck"),
					91 -> new key("(kbdm_PAGE_STD     + 0x05F)","KP 7"),
					92 -> new key("(kbdm_PAGE_STD     + 0x05C)","KP 4"),
					93 -> new key("(kbdm_PAGE_STD     + 0x059)","KP 1"),
					95 -> new key("(kbdm_PAGE_STD     + 0x054)","KP /"),
					96 -> new key("(kbdm_PAGE_STD     + 0x060)","KP 8"),
					97 -> new key("(kbdm_PAGE_STD     + 0x05D)","KP 5"),
					98 -> new key("(kbdm_PAGE_STD     + 0x05A)","KP 2"),
					99 -> new key("(kbdm_PAGE_STD     + 0x062)","KP 0"),
					100 -> new key("(kbdm_PAGE_STD     + 0x055)","KP *"),
					101 -> new key("(kbdm_PAGE_STD     + 0x061)","KP 9"),
					102 -> new key("(kbdm_PAGE_STD     + 0x05E)","KP 6"),
					103 -> new key("(kbdm_PAGE_STD     + 0x05B)","KP 3"),
					104 -> new key("(kbdm_PAGE_STD     + 0x063)","KP ."),
					105 -> new key("(kbdm_PAGE_STD     + 0x056)","KP -"),
					106 -> new key("(kbdm_PAGE_STD     + 0x057)","KP +"),
					107 -> new key("(kbdm_PAGE_STD     + 0x0XX)","KP comma"),
					108 -> new key("(kbdm_PAGE_STD     + 0x058)","KP Enter"),
					110 -> new key("(kbdm_PAGE_STD     + 0x029)","Esc"),
					112 -> new key("(kbdm_PAGE_STD     + 0x03A)","F1"),
					113 -> new key("(kbdm_PAGE_STD     + 0x03B)","F2"),
					114 -> new key("(kbdm_PAGE_STD     + 0x03C)","F3"),
					115 -> new key("(kbdm_PAGE_STD     + 0x03D)","F4"),
					116 -> new key("(kbdm_PAGE_STD     + 0x03E)","F5"),
					117 -> new key("(kbdm_PAGE_STD     + 0x03F)","F6"),
					118 -> new key("(kbdm_PAGE_STD     + 0x040)","F7"),
					119 -> new key("(kbdm_PAGE_STD     + 0x041)","F8"),
					120 -> new key("(kbdm_PAGE_STD     + 0x042)","F9"),
					121 -> new key("(kbdm_PAGE_STD     + 0x043)","F10"),
					122 -> new key("(kbdm_PAGE_STD     + 0x044)","F11"),
					123 -> new key("(kbdm_PAGE_STD     + 0x045)","F12"),
					124 -> new key("(kbdm_PAGE_STD     + 0x046)","PrntScrn"),
					125 -> new key("(kbdm_PAGE_STD     + 0x047)","ScrLck"),
					126 -> new key("(kbdm_PAGE_STD     + 0x048)","PauseBrk"),
					131 -> new key("(kbdm_PAGE_STD     + 0x065)","App"),
					132 -> new key("(kbdm_PAGE_STD     + 0x08B)","Muhenkan"),
					133 -> new key("(kbdm_PAGE_STD     + 0x08A)","Henkan"),
					134 -> new key("(kbdm_PAGE_STD     + 0x088)","KataHira"),
					135 -> new key("(kbdm_PAGE_STD     + 0x091)","Hanja"),
					136 -> new key("(kbdm_PAGE_STD     + 0x090)","Hanguel"),
					137 -> new key("(kbdm_PAGE_STD     + 0x067)","KP="),
					141 -> new key("(kbdm_PAGE_MBT     + 0x001)","L-Button","kbdm_KT_"),
					142 -> new key("(kbdm_PAGE_MBT     + 0x002)","R-Button","kbdm_KT_"),
					143 -> new key("(kbdm_PAGE_STD     + 0x0XX)","M-Button"),
					147 -> new key("(0x000 + kbdm_CLR_PAGE    )","Clear all"),
					151 -> new key("(kbdm_PAGE_LOCAL          )","L-Fn","kbdm_KT_FN"),
					152 -> new key("(0x02C + kbdm_BUTTON_PAGE )","R-Fn","kbdm_KT_FN"),


					263 -> new key("(0x02C + kbdm_BUTTON_PAGE)","FnKeyMAC","kbdm_KT_FN"),
					264 -> new key("(kbdm_PAGE_STD     + 0x068)","F13"),
					265 -> new key("(kbdm_PAGE_STD     + 0x069)","F14"),
					266 -> new key("(kbdm_PAGE_STD     + 0x06A)","F15"),
					267 -> new key("(kbdm_PAGE_STD     + 0x06B)","F16"),
					268 -> new key("(kbdm_PAGE_STD     + 0x06C)","F17"),
					269 -> new key("(kbdm_PAGE_STD     + 0x06D)","F18"),
					270 -> new key("(kbdm_PAGE_STD     + 0x06E)","F19"),
					271 -> new key("(0x06F + kbdm_BUTTON_PAGE)","Bright-"),
					272 -> new key("(0x06E + kbdm_BUTTON_PAGE)","Bright+"),
					273 -> new key("(0x03E + kbdm_BUTTON_PAGE)","Present"),
					274 -> new key("(0x03D + kbdm_BUTTON_PAGE)","Dashbrd"),
					275 -> new key("(0x045 + kbdm_BUTTON_PAGE)","F5"),
					276 -> new key("(0x046 + kbdm_BUTTON_PAGE)","F6"),
					277 -> new key("(0x000 + kbdm_UNDEF_PAGE )","Prev Track"),
					278 -> new key("(0x0CD + kbdm_CONSUM_PAGE)","Play / Pause"),
					279 -> new key("(0x000 + kbdm_UNDEF_PAGE )","Next Track"),
					280 -> new key("(kbdm_PAGE_CONS    + 0x0e2)","Mute"),
					281 -> new key("(kbdm_PAGE_CONS    + 0x0ea)","Vol-"),
					282 -> new key("(kbdm_PAGE_CONS    + 0x0e9)","Vol+"),
					283 -> new key("(0x06B + kbdm_BUTTON_PAGE)","CoverFlow"),
					284 -> new key("(0x06C + kbdm_BUTTON_PAGE)","QuickLook"),
					285 -> new key("(0x06D + kbdm_BUTTON_PAGE)","Spaces"),
					286 -> new key("(0x183 + kbdm_CONSUM_PAGE)","iTunes"),
					287 -> new key("(0x18A + kbdm_CONSUM_PAGE)","Email"),
					289 -> new key("(0x192 + kbdm_CONSUM_PAGE)","iCalc"),


					400 -> new key("(0x0D8 + kbdm_KBD_PAGE   )","Keypad Clear"),
					401 -> new key("(0x0B6 + kbdm_KBD_PAGE   )","Keypad Left Parenthesis"),
					402 -> new key("(0x0B7 + kbdm_KBD_PAGE   )","Keypad Right Parenthesis"),

					409 -> new key("(0x001 + kbdm_CONSUM_PAGE)","Consumer Control"),
					410 -> new key("(0x002 + kbdm_CONSUM_PAGE)","Numeric Key Pad"),
					411 -> new key("(0x003 + kbdm_CONSUM_PAGE)","Programmable Buttons"),
					412 -> new key("(0x004 + kbdm_CONSUM_PAGE)","Microphone"),
					413 -> new key("(0x005 + kbdm_CONSUM_PAGE)","Headphone"),
					414 -> new key("(0x006 + kbdm_CONSUM_PAGE)","Graphic Equalizer"),
					415 -> new key("(0x020 + kbdm_CONSUM_PAGE)","+10"),
					416 -> new key("(0x021 + kbdm_CONSUM_PAGE)","+100"),
					417 -> new key("(0x022 + kbdm_CONSUM_PAGE)","AM/PM"),
					418 -> new key("(0x030 + kbdm_CONSUM_PAGE)","Power"),
					419 -> new key("(0x031 + kbdm_CONSUM_PAGE)","Reset"),
					420 -> new key("(0x032 + kbdm_CONSUM_PAGE)","Sleep"),
					421 -> new key("(0x033 + kbdm_CONSUM_PAGE)","Sleep After"),
					422 -> new key("(0x034 + kbdm_CONSUM_PAGE)","Sleep Mode"),
					423 -> new key("(0x035 + kbdm_CONSUM_PAGE)","Illumination"),
					424 -> new key("(0x036 + kbdm_CONSUM_PAGE)","Function Buttons"),
					425 -> new key("(0x040 + kbdm_CONSUM_PAGE)","Menu"),
					426 -> new key("(0x041 + kbdm_CONSUM_PAGE)","Menu Pick"),
					427 -> new key("(0x042 + kbdm_CONSUM_PAGE)","Menu Up"),
					428 -> new key("(0x043 + kbdm_CONSUM_PAGE)","Menu Down"),
					429 -> new key("(0x044 + kbdm_CONSUM_PAGE)","Menu Left"),
					430 -> new key("(0x045 + kbdm_CONSUM_PAGE)","Menu Right"),
					431 -> new key("(0x046 + kbdm_CONSUM_PAGE)","Menu Escape"),
					432 -> new key("(0x047 + kbdm_CONSUM_PAGE)","Menu Value Increase"),
					433 -> new key("(0x048 + kbdm_CONSUM_PAGE)","Menu Value Decrease"),
					434 -> new key("(0x060 + kbdm_CONSUM_PAGE)","Data On Screen"),
					435 -> new key("(0x061 + kbdm_CONSUM_PAGE)","Closed Caption"),
					436 -> new key("(0x062 + kbdm_CONSUM_PAGE)","Closed Caption Select"),
					437 -> new key("(0x063 + kbdm_CONSUM_PAGE)","VCR/TV"),
					438 -> new key("(0x064 + kbdm_CONSUM_PAGE)","Broadcast Mode"),
					439 -> new key("(0x065 + kbdm_CONSUM_PAGE)","Snapshot"),
					440 -> new key("(0x066 + kbdm_CONSUM_PAGE)","Still"),
					441 -> new key("(0x080 + kbdm_CONSUM_PAGE)","Selection"),
					442 -> new key("(0x081 + kbdm_CONSUM_PAGE)","Assign Selection"),
					443 -> new key("(0x082 + kbdm_CONSUM_PAGE)","Mode Step"),
					444 -> new key("(0x083 + kbdm_CONSUM_PAGE)","Recall Last"),
					445 -> new key("(0x084 + kbdm_CONSUM_PAGE)","Enter Channel"),
					446 -> new key("(0x085 + kbdm_CONSUM_PAGE)","Order Movie"),
					447 -> new key("(0x086 + kbdm_CONSUM_PAGE)","Channel"),
					448 -> new key("(0x087 + kbdm_CONSUM_PAGE)","Media Selection"),
					449 -> new key("(0x088 + kbdm_CONSUM_PAGE)","Media Select Computer"),
					450 -> new key("(0x089 + kbdm_CONSUM_PAGE)","Media Select TV"),
					451 -> new key("(0x08A + kbdm_CONSUM_PAGE)","Media Select WWW"),
					452 -> new key("(0x08B + kbdm_CONSUM_PAGE)","Media Select DVD"),
					453 -> new key("(0x08C + kbdm_CONSUM_PAGE)","Media Select Telephone"),
					454 -> new key("(0x08D + kbdm_CONSUM_PAGE)","Media Select Program Guide"),
					455 -> new key("(0x08E + kbdm_CONSUM_PAGE)","Media Select Video Phone"),
					456 -> new key("(0x08F + kbdm_CONSUM_PAGE)","Media Select Games"),
					457 -> new key("(0x090 + kbdm_CONSUM_PAGE)","Media Select Messages"),
					458 -> new key("(0x091 + kbdm_CONSUM_PAGE)","Media Select CD"),
					459 -> new key("(0x092 + kbdm_CONSUM_PAGE)","Media Select VCR"),
					460 -> new key("(0x093 + kbdm_CONSUM_PAGE)","Media Select Tuner"),
					461 -> new key("(0x094 + kbdm_CONSUM_PAGE)","Quit"),
					462 -> new key("(0x095 + kbdm_CONSUM_PAGE)","Help"),
					463 -> new key("(0x096 + kbdm_CONSUM_PAGE)","Media Select Tape"),
					464 -> new key("(0x097 + kbdm_CONSUM_PAGE)","Media Select Cable"),
					465 -> new key("(0x098 + kbdm_CONSUM_PAGE)","Media Select Satellite"),
					466 -> new key("(0x099 + kbdm_CONSUM_PAGE)","Media Select Security"),
					467 -> new key("(0x09A + kbdm_CONSUM_PAGE)","Media Select Home"),
					468 -> new key("(0x09B + kbdm_CONSUM_PAGE)","Media Select Call"),
					469 -> new key("(0x09C + kbdm_CONSUM_PAGE)","Channel Increment"),
					470 -> new key("(0x09D + kbdm_CONSUM_PAGE)","Channel Decrement"),
					471 -> new key("(0x09E + kbdm_CONSUM_PAGE)","Media Select"),
					472 -> new key("(0x0A0 + kbdm_CONSUM_PAGE)","VCR Plus"),
					473 -> new key("(0x0A1 + kbdm_CONSUM_PAGE)","Once"),
					474 -> new key("(0x0A2 + kbdm_CONSUM_PAGE)","Daily"),
					475 -> new key("(0x0A3 + kbdm_CONSUM_PAGE)","Weekly"),
					476 -> new key("(0x0A4 + kbdm_CONSUM_PAGE)","Monthly"),
					477 -> new key("(0x0B0 + kbdm_CONSUM_PAGE)","Play"),
					478 -> new key("(0x0B1 + kbdm_CONSUM_PAGE)","Pause"),
					479 -> new key("(0x0B2 + kbdm_CONSUM_PAGE)","Record"),
					480 -> new key("(0x0B3 + kbdm_CONSUM_PAGE)","Fast Forward"),
					481 -> new key("(0x0B4 + kbdm_CONSUM_PAGE)","Rewind"),
					482 -> new key("(0x0B5 + kbdm_CONSUM_PAGE)","Scan Next Track"),
					483 -> new key("(0x0B6 + kbdm_CONSUM_PAGE)","Scan Previous Track"),
					484 -> new key("(0x0B7 + kbdm_CONSUM_PAGE)","Stop"),
					485 -> new key("(0x0B8 + kbdm_CONSUM_PAGE)","Eject"),
					486 -> new key("(0x0B9 + kbdm_CONSUM_PAGE)","Random Play"),
					487 -> new key("(0x0BA + kbdm_CONSUM_PAGE)","Select Disc"),
					488 -> new key("(0x0BB + kbdm_CONSUM_PAGE)","Enter Disc"),
					489 -> new key("(0x0BC + kbdm_CONSUM_PAGE)","Repeat"),
					490 -> new key("(0x0BD + kbdm_CONSUM_PAGE)","Tracking"),
					491 -> new key("(0x0BE + kbdm_CONSUM_PAGE)","Track Normal"),
					492 -> new key("(0x0BF + kbdm_CONSUM_PAGE)","Slow Tracking"),
					493 -> new key("(0x0C0 + kbdm_CONSUM_PAGE)","Frame Forward"),
					494 -> new key("(0x0C1 + kbdm_CONSUM_PAGE)","Frame Back"),
					495 -> new key("(0x0C2 + kbdm_CONSUM_PAGE)","Mark"),
					496 -> new key("(0x0C3 + kbdm_CONSUM_PAGE)","Clear Mark"),
					497 -> new key("(0x0C4 + kbdm_CONSUM_PAGE)","Repeat From Mark"),
					498 -> new key("(0x0C5 + kbdm_CONSUM_PAGE)","Return To Mark"),
					499 -> new key("(0x0C6 + kbdm_CONSUM_PAGE)","Search Mark Forward"),
					500 -> new key("(0x0C7 + kbdm_CONSUM_PAGE)","Search Mark Backwards"),
					501 -> new key("(0x0C8 + kbdm_CONSUM_PAGE)","Counter Reset"),
					502 -> new key("(0x0C9 + kbdm_CONSUM_PAGE)","Show Counter"),
					503 -> new key("(0x0CA + kbdm_CONSUM_PAGE)","Tracking Increment"),
					504 -> new key("(0x0CB + kbdm_CONSUM_PAGE)","Tracking Decrement"),
					505 -> new key("(0x0CC + kbdm_CONSUM_PAGE)","Stop/Eject"),
					506 -> new key("(0x0CD + kbdm_CONSUM_PAGE)","Play/Pause"),
					507 -> new key("(0x0CE + kbdm_CONSUM_PAGE)","Play/Skip"),
					508 -> new key("(0x0E0 + kbdm_CONSUM_PAGE)","Volume"),
					509 -> new key("(0x0E1 + kbdm_CONSUM_PAGE)","Balance"),
					510 -> new key("(0x0E2 + kbdm_CONSUM_PAGE)","Mute"),
					511 -> new key("(0x0E3 + kbdm_CONSUM_PAGE)","Bass"),
					512 -> new key("(0x0E4 + kbdm_CONSUM_PAGE)","Treble"),
					513 -> new key("(0x0E5 + kbdm_CONSUM_PAGE)","Bass Boost"),
					514 -> new key("(0x0E6 + kbdm_CONSUM_PAGE)","Surround Mode"),
					515 -> new key("(0x0E7 + kbdm_CONSUM_PAGE)","Loudness"),
					516 -> new key("(0x0E8 + kbdm_CONSUM_PAGE)","MPX"),
					517 -> new key("(0x0E9 + kbdm_CONSUM_PAGE)","Volume Increment"),
					518 -> new key("(0x0EA + kbdm_CONSUM_PAGE)","Volume Decrement"),
					519 -> new key("(0x0F0 + kbdm_CONSUM_PAGE)","Speed Select"),
					520 -> new key("(0x0F1 + kbdm_CONSUM_PAGE)","Playback Speed"),
					521 -> new key("(0x0F2 + kbdm_CONSUM_PAGE)","Standard Play"),
					522 -> new key("(0x0F3 + kbdm_CONSUM_PAGE)","Long Play"),
					523 -> new key("(0x0F4 + kbdm_CONSUM_PAGE)","Extended Play"),
					524 -> new key("(0x0F5 + kbdm_CONSUM_PAGE)","Slow"),
					525 -> new key("(0x100 + kbdm_CONSUM_PAGE)","Fan Enable"),
					526 -> new key("(0x101 + kbdm_CONSUM_PAGE)","Fan Speed"),
					527 -> new key("(0x102 + kbdm_CONSUM_PAGE)","Light Enable"),
					528 -> new key("(0x103 + kbdm_CONSUM_PAGE)","Light Illumination Level"),
					529 -> new key("(0x104 + kbdm_CONSUM_PAGE)","Climate Control Enable"),
					530 -> new key("(0x105 + kbdm_CONSUM_PAGE)","Room Temperature"),
					531 -> new key("(0x106 + kbdm_CONSUM_PAGE)","Security Enable"),
					532 -> new key("(0x109 + kbdm_CONSUM_PAGE)","Proximity"),
					533 -> new key("(0x10A + kbdm_CONSUM_PAGE)","Motion"),
					534 -> new key("(0x150 + kbdm_CONSUM_PAGE)","Balance Right"),
					535 -> new key("(0x151 + kbdm_CONSUM_PAGE)","Balance Left"),
					536 -> new key("(0x152 + kbdm_CONSUM_PAGE)","Bass Increment"),
					537 -> new key("(0x153 + kbdm_CONSUM_PAGE)","Bass Decrement"),
					538 -> new key("(0x154 + kbdm_CONSUM_PAGE)","Treble Increment"),
					539 -> new key("(0x155 + kbdm_CONSUM_PAGE)","Treble Decrement"),
					540 -> new key("(0x160 + kbdm_CONSUM_PAGE)","Speaker System"),
					541 -> new key("(0x161 + kbdm_CONSUM_PAGE)","Channel Left"),
					542 -> new key("(0x162 + kbdm_CONSUM_PAGE)","Channel Right"),
					543 -> new key("(0x163 + kbdm_CONSUM_PAGE)","Channel Center"),
					544 -> new key("(0x164 + kbdm_CONSUM_PAGE)","Channel Front"),
					545 -> new key("(0x165 + kbdm_CONSUM_PAGE)","Channel Center Front"),
					546 -> new key("(0x166 + kbdm_CONSUM_PAGE)","Channel Side"),
					547 -> new key("(0x167 + kbdm_CONSUM_PAGE)","Channel Surround"),
					548 -> new key("(0x168 + kbdm_CONSUM_PAGE)","Channel Low Frequency Enhancement"),
					549 -> new key("(0x169 + kbdm_CONSUM_PAGE)","Channel Top"),
					550 -> new key("(0x16A + kbdm_CONSUM_PAGE)","Channel Unknown"),
					551 -> new key("(0x170 + kbdm_CONSUM_PAGE)","Sub-channel"),
					552 -> new key("(0x171 + kbdm_CONSUM_PAGE)","Sub-channel Increment"),
					553 -> new key("(0x172 + kbdm_CONSUM_PAGE)","Sub-channel Decrement"),
					554 -> new key("(0x173 + kbdm_CONSUM_PAGE)","Alternate Audio Increment"),
					555 -> new key("(0x174 + kbdm_CONSUM_PAGE)","Alternate Audio Decrement"),
					556 -> new key("(0x180 + kbdm_CONSUM_PAGE)","Application Launch Buttons"),
					557 -> new key("(0x181 + kbdm_CONSUM_PAGE)","AL Launch Button Configuration Tool"),
					558 -> new key("(0x182 + kbdm_CONSUM_PAGE)","AL Programmable Button Configuration"),
					559 -> new key("(0x183 + kbdm_CONSUM_PAGE)","AL Consumer Control Configuration"),
					560 -> new key("(0x184 + kbdm_CONSUM_PAGE)","AL Word Processor"),
					561 -> new key("(0x185 + kbdm_CONSUM_PAGE)","AL Text Editor"),
					562 -> new key("(0x186 + kbdm_CONSUM_PAGE)","AL Spreadsheet"),
					563 -> new key("(0x187 + kbdm_CONSUM_PAGE)","AL Graphics Editor"),
					564 -> new key("(0x188 + kbdm_CONSUM_PAGE)","AL Presentation App"),
					565 -> new key("(0x189 + kbdm_CONSUM_PAGE)","AL Database App"),
					566 -> new key("(0x18A + kbdm_CONSUM_PAGE)","AL Email Reader"),
					567 -> new key("(0x18B + kbdm_CONSUM_PAGE)","AL Newsreader"),
					568 -> new key("(0x18C + kbdm_CONSUM_PAGE)","AL Voicemail"),
					569 -> new key("(0x18D + kbdm_CONSUM_PAGE)","AL Contacts/Address Book"),
					570 -> new key("(0x18E + kbdm_CONSUM_PAGE)","AL Calendar/Schedule"),
					571 -> new key("(0x18F + kbdm_CONSUM_PAGE)","AL Task/Project Manager"),
					572 -> new key("(0x190 + kbdm_CONSUM_PAGE)","AL Log/Journal/Timecard"),
					573 -> new key("(0x191 + kbdm_CONSUM_PAGE)","AL Checkbook/Finance"),
					574 -> new key("(0x192 + kbdm_CONSUM_PAGE)","AL Calculator"),
					575 -> new key("(0x193 + kbdm_CONSUM_PAGE)","AL A/V Capture/Playback"),
					576 -> new key("(0x194 + kbdm_CONSUM_PAGE)","AL Local Machine Browser"),
					577 -> new key("(0x195 + kbdm_CONSUM_PAGE)","AL LAN/WAN Browser"),
					578 -> new key("(0x196 + kbdm_CONSUM_PAGE)","AL Internet Browser"),
					579 -> new key("(0x197 + kbdm_CONSUM_PAGE)","AL Remote Networking/ISP Connect"),
					580 -> new key("(0x198 + kbdm_CONSUM_PAGE)","AL Network Conference"),
					581 -> new key("(0x199 + kbdm_CONSUM_PAGE)","AL Network Chat"),
					582 -> new key("(0x19A + kbdm_CONSUM_PAGE)","AL Telephony/Dialer"),
					583 -> new key("(0x19B + kbdm_CONSUM_PAGE)","AL Logon"),
					584 -> new key("(0x19C + kbdm_CONSUM_PAGE)","AL Logoff"),
					585 -> new key("(0x19D + kbdm_CONSUM_PAGE)","AL Logon/Logoff"),
					586 -> new key("(0x19E + kbdm_CONSUM_PAGE)","AL Terminal Lock/Screensaver"),
					587 -> new key("(0x19F + kbdm_CONSUM_PAGE)","AL Control Panel"),
					588 -> new key("(0x1A0 + kbdm_CONSUM_PAGE)","AL Command Line Processor/Run"),
					589 -> new key("(0x1A1 + kbdm_CONSUM_PAGE)","AL Process/Task Manager"),
					590 -> new key("(0x1A2 + kbdm_CONSUM_PAGE)","AL Select Task/Application"),
					591 -> new key("(0x1A3 + kbdm_CONSUM_PAGE)","AL Next Task/Application"),
					592 -> new key("(0x1A4 + kbdm_CONSUM_PAGE)","AL Previous Task/Application"),
					593 -> new key("(0x1A5 + kbdm_CONSUM_PAGE)","AL Preemptive Halt Task/Application"),
					594 -> new key("(0x1A6 + kbdm_CONSUM_PAGE)","AL Integrated Help Center"),
					595 -> new key("(0x1A7 + kbdm_CONSUM_PAGE)","AL Documents"),
					596 -> new key("(0x1A8 + kbdm_CONSUM_PAGE)","AL Thesaurus"),
					597 -> new key("(0x1A9 + kbdm_CONSUM_PAGE)","AL Dictionary"),
					598 -> new key("(0x1AA + kbdm_CONSUM_PAGE)","AL Desktop"),
					599 -> new key("(0x1AB + kbdm_CONSUM_PAGE)","AL Spell Check"),
					600 -> new key("(0x1AC + kbdm_CONSUM_PAGE)","AL Grammar Check"),
					601 -> new key("(0x1AD + kbdm_CONSUM_PAGE)","AL Wireless Status"),
					602 -> new key("(0x1AE + kbdm_CONSUM_PAGE)","AL Keyboard Layout"),
					603 -> new key("(0x1AF + kbdm_CONSUM_PAGE)","AL Virus Protection"),
					604 -> new key("(0x1B0 + kbdm_CONSUM_PAGE)","AL Encryption"),
					605 -> new key("(0x1B1 + kbdm_CONSUM_PAGE)","AL Screen Saver"),
					606 -> new key("(0x1B2 + kbdm_CONSUM_PAGE)","AL Alarms"),
					607 -> new key("(0x1B3 + kbdm_CONSUM_PAGE)","AL Clock"),
					608 -> new key("(0x1B4 + kbdm_CONSUM_PAGE)","AL File Browser"),
					609 -> new key("(0x1B5 + kbdm_CONSUM_PAGE)","AL Power Status"),
					610 -> new key("(0x1B6 + kbdm_CONSUM_PAGE)","AL Image Browser"),
					611 -> new key("(0x1B7 + kbdm_CONSUM_PAGE)","AL Audio Browser"),
					612 -> new key("(0x1B8 + kbdm_CONSUM_PAGE)","AL Movie Browser"),
					613 -> new key("(0x1B9 + kbdm_CONSUM_PAGE)","AL Digital Rights Manager"),
					614 -> new key("(0x1BA + kbdm_CONSUM_PAGE)","AL Digital Wallet"),
					615 -> new key("(0x1BC + kbdm_CONSUM_PAGE)","AL Instant Messaging"),
					616 -> new key("(0x1BD + kbdm_CONSUM_PAGE)","AL OEM Features/Tips/Tutorial Browser"),
					617 -> new key("(0x1BE + kbdm_CONSUM_PAGE)","AL OEM Help"),
					618 -> new key("(0x1BF + kbdm_CONSUM_PAGE)","AL Online Community"),
					619 -> new key("(0x1C0 + kbdm_CONSUM_PAGE)","AL Entertainment Content Browser"),
					620 -> new key("(0x1C1 + kbdm_CONSUM_PAGE)","AL Online Shopping Browser"),
					621 -> new key("(0x1C2 + kbdm_CONSUM_PAGE)","AL SmartCard Information/Help"),
					622 -> new key("(0x1C3 + kbdm_CONSUM_PAGE)","AL Market Monitor/Finance Browser"),
					623 -> new key("(0x1C4 + kbdm_CONSUM_PAGE)","AL Customized Corporate News Browser"),
					624 -> new key("(0x1C5 + kbdm_CONSUM_PAGE)","AL Online Activity Browser"),
					625 -> new key("(0x1C6 + kbdm_CONSUM_PAGE)","AL Research/Search Browser"),
					626 -> new key("(0x1C7 + kbdm_CONSUM_PAGE)","AL Audio Player"),
					627 -> new key("(0x200 + kbdm_CONSUM_PAGE)","Generic GUI Application Controls"),
					628 -> new key("(0x201 + kbdm_CONSUM_PAGE)","AC New"),
					629 -> new key("(0x202 + kbdm_CONSUM_PAGE)","AC Open"),
					630 -> new key("(0x203 + kbdm_CONSUM_PAGE)","AC Close"),
					631 -> new key("(0x204 + kbdm_CONSUM_PAGE)","AC Exit"),
					632 -> new key("(0x205 + kbdm_CONSUM_PAGE)","AC Maximize"),
					633 -> new key("(0x206 + kbdm_CONSUM_PAGE)","AC Minimize"),
					634 -> new key("(0x207 + kbdm_CONSUM_PAGE)","AC Save"),
					635 -> new key("(0x208 + kbdm_CONSUM_PAGE)","AC Print"),
					636 -> new key("(0x209 + kbdm_CONSUM_PAGE)","AC Properties"),
					637 -> new key("(0x21A + kbdm_CONSUM_PAGE)","AC Undo"),
					638 -> new key("(0x21B + kbdm_CONSUM_PAGE)","AC Copy"),
					639 -> new key("(0x21C + kbdm_CONSUM_PAGE)","AC Cut"),
					640 -> new key("(0x21D + kbdm_CONSUM_PAGE)","AC Paste"),
					641 -> new key("(0x21E + kbdm_CONSUM_PAGE)","AC Select All"),
					642 -> new key("(0x21F + kbdm_CONSUM_PAGE)","AC Find"),
					643 -> new key("(0x220 + kbdm_CONSUM_PAGE)","AC Find and Replace"),
					644 -> new key("(0x221 + kbdm_CONSUM_PAGE)","AC Search"),
					645 -> new key("(0x222 + kbdm_CONSUM_PAGE)","AC Go To"),
					646 -> new key("(kbdm_PAGE_CONS    + 0x223)","AC Home"),
					647 -> new key("(0x224 + kbdm_CONSUM_PAGE)","AC Back"),
					648 -> new key("(0x225 + kbdm_CONSUM_PAGE)","AC Forward"),
					649 -> new key("(0x226 + kbdm_CONSUM_PAGE)","AC Stop"),
					650 -> new key("(0x227 + kbdm_CONSUM_PAGE)","AC Refresh"),
					651 -> new key("(0x228 + kbdm_CONSUM_PAGE)","AC Previous Link"),
					652 -> new key("(0x229 + kbdm_CONSUM_PAGE)","AC Next Link"),
					653 -> new key("(0x22A + kbdm_CONSUM_PAGE)","AC Bookmarks"),
					654 -> new key("(0x22B + kbdm_CONSUM_PAGE)","AC History"),
					655 -> new key("(0x22C + kbdm_CONSUM_PAGE)","AC Subscriptions"),
					656 -> new key("(0x22D + kbdm_CONSUM_PAGE)","AC Zoom In"),
					657 -> new key("(0x22E + kbdm_CONSUM_PAGE)","AC Zoom Out"),
					658 -> new key("(0x22F + kbdm_CONSUM_PAGE)","AC Zoom"),
					659 -> new key("(0x230 + kbdm_CONSUM_PAGE)","AC Full Screen View"),
					660 -> new key("(0x231 + kbdm_CONSUM_PAGE)","AC Normal View"),
					661 -> new key("(0x232 + kbdm_CONSUM_PAGE)","AC View Toggle"),
					662 -> new key("(0x233 + kbdm_CONSUM_PAGE)","AC Scroll Up"),
					663 -> new key("(0x234 + kbdm_CONSUM_PAGE)","AC Scroll Down"),
					664 -> new key("(0x235 + kbdm_CONSUM_PAGE)","AC Scroll"),
					665 -> new key("(0x236 + kbdm_CONSUM_PAGE)","AC Pan Left"),
					666 -> new key("(0x237 + kbdm_CONSUM_PAGE)","AC Pan Right"),
					667 -> new key("(0x238 + kbdm_CONSUM_PAGE)","AC Pan"),
					668 -> new key("(0x239 + kbdm_CONSUM_PAGE)","AC New Window"),
					669 -> new key("(0x23A + kbdm_CONSUM_PAGE)","AC Tile Horizontally"),
					670 -> new key("(0x23B + kbdm_CONSUM_PAGE)","AC Tile Vertically"),
					671 -> new key("(0x23C + kbdm_CONSUM_PAGE)","AC Format"),
					672 -> new key("(0x23D + kbdm_CONSUM_PAGE)","AC Edit"),
					673 -> new key("(0x23E + kbdm_CONSUM_PAGE)","AC Bold"),
					674 -> new key("(0x23F + kbdm_CONSUM_PAGE)","AC Italics"),
					675 -> new key("(0x240 + kbdm_CONSUM_PAGE)","AC Underline"),
					676 -> new key("(0x241 + kbdm_CONSUM_PAGE)","AC Strikethrough"),
					677 -> new key("(0x242 + kbdm_CONSUM_PAGE)","AC Subscript"),
					678 -> new key("(0x243 + kbdm_CONSUM_PAGE)","AC Superscript"),
					679 -> new key("(0x244 + kbdm_CONSUM_PAGE)","AC All Caps"),
					680 -> new key("(0x245 + kbdm_CONSUM_PAGE)","AC Rotate"),
					681 -> new key("(0x246 + kbdm_CONSUM_PAGE)","AC Resize"),
					682 -> new key("(0x247 + kbdm_CONSUM_PAGE)","AC Flip horizontal"),
					683 -> new key("(0x248 + kbdm_CONSUM_PAGE)","AC Flip Vertical"),
					684 -> new key("(0x249 + kbdm_CONSUM_PAGE)","AC Mirror Horizontal"),
					685 -> new key("(0x24A + kbdm_CONSUM_PAGE)","AC Mirror Vertical"),
					686 -> new key("(0x24B + kbdm_CONSUM_PAGE)","AC Font Select"),
					687 -> new key("(0x24C + kbdm_CONSUM_PAGE)","AC Font Color"),
					688 -> new key("(0x24D + kbdm_CONSUM_PAGE)","AC Font Size"),
					689 -> new key("(0x24E + kbdm_CONSUM_PAGE)","AC Justify Left"),
					690 -> new key("(0x24F + kbdm_CONSUM_PAGE)","AC Justify Center H"),
					691 -> new key("(0x250 + kbdm_CONSUM_PAGE)","AC Justify Right"),
					692 -> new key("(0x251 + kbdm_CONSUM_PAGE)","AC Justify Block H"),
					693 -> new key("(0x252 + kbdm_CONSUM_PAGE)","AC Justify Top"),
					694 -> new key("(0x253 + kbdm_CONSUM_PAGE)","AC Justify Center V"),
					695 -> new key("(0x254 + kbdm_CONSUM_PAGE)","AC Justify Bottom"),
					696 -> new key("(0x255 + kbdm_CONSUM_PAGE)","AC Justify Block V"),
					697 -> new key("(0x256 + kbdm_CONSUM_PAGE)","AC Indent Decrease"),
					698 -> new key("(0x257 + kbdm_CONSUM_PAGE)","AC Indent Increase"),
					699 -> new key("(0x258 + kbdm_CONSUM_PAGE)","AC Numbered List"),
					700 -> new key("(0x259 + kbdm_CONSUM_PAGE)","AC Restart Numbering"),
					701 -> new key("(0x25A + kbdm_CONSUM_PAGE)","AC Bulleted List"),
					702 -> new key("(0x25B + kbdm_CONSUM_PAGE)","AC Promote"),
					703 -> new key("(0x25C + kbdm_CONSUM_PAGE)","AC Demote"),
					704 -> new key("(0x25D + kbdm_CONSUM_PAGE)","AC Yes"),
					705 -> new key("(0x25E + kbdm_CONSUM_PAGE)","AC No"),
					706 -> new key("(0x25F + kbdm_CONSUM_PAGE)","AC Cancel"),
					707 -> new key("(0x260 + kbdm_CONSUM_PAGE)","AC Catalog"),
					708 -> new key("(0x261 + kbdm_CONSUM_PAGE)","AC Buy/Checkout"),
					709 -> new key("(0x262 + kbdm_CONSUM_PAGE)","AC Add to Cart"),
					710 -> new key("(0x263 + kbdm_CONSUM_PAGE)","AC Expand"),
					711 -> new key("(0x264 + kbdm_CONSUM_PAGE)","AC Expand All"),
					712 -> new key("(0x265 + kbdm_CONSUM_PAGE)","AC Collapse"),
					713 -> new key("(0x266 + kbdm_CONSUM_PAGE)","AC Collapse All"),
					714 -> new key("(0x267 + kbdm_CONSUM_PAGE)","AC Print Preview"),
					715 -> new key("(0x268 + kbdm_CONSUM_PAGE)","AC Paste Special"),
					716 -> new key("(0x269 + kbdm_CONSUM_PAGE)","AC Insert Mode"),
					717 -> new key("(0x26A + kbdm_CONSUM_PAGE)","AC Delete"),
					718 -> new key("(0x26B + kbdm_CONSUM_PAGE)","AC Lock"),
					719 -> new key("(0x26C + kbdm_CONSUM_PAGE)","AC Unlock"),
					720 -> new key("(0x26D + kbdm_CONSUM_PAGE)","AC Protect"),
					721 -> new key("(0x26E + kbdm_CONSUM_PAGE)","AC Unprotect"),
					722 -> new key("(0x26F + kbdm_CONSUM_PAGE)","AC Attach Comment"),
					723 -> new key("(0x270 + kbdm_CONSUM_PAGE)","AC Delete Comment"),
					724 -> new key("(0x271 + kbdm_CONSUM_PAGE)","AC View Comment"),
					725 -> new key("(0x272 + kbdm_CONSUM_PAGE)","AC Select Word"),
					726 -> new key("(0x273 + kbdm_CONSUM_PAGE)","AC Select Sentence"),
					727 -> new key("(0x274 + kbdm_CONSUM_PAGE)","AC Select Paragraph"),
					728 -> new key("(0x275 + kbdm_CONSUM_PAGE)","AC Select Column"),
					729 -> new key("(0x276 + kbdm_CONSUM_PAGE)","AC Select Row"),
					730 -> new key("(0x277 + kbdm_CONSUM_PAGE)","AC Select Table"),
					731 -> new key("(0x278 + kbdm_CONSUM_PAGE)","AC Select Object"),
					732 -> new key("(0x279 + kbdm_CONSUM_PAGE)","AC Redo/Repeat"),
					733 -> new key("(0x27A + kbdm_CONSUM_PAGE)","AC Sort"),
					734 -> new key("(0x27B + kbdm_CONSUM_PAGE)","AC Sort Ascending"),
					735 -> new key("(0x27C + kbdm_CONSUM_PAGE)","AC Sort Descending"),
					736 -> new key("(0x27D + kbdm_CONSUM_PAGE)","AC Filter"),
					737 -> new key("(0x27E + kbdm_CONSUM_PAGE)","AC Set Clock"),
					738 -> new key("(0x27F + kbdm_CONSUM_PAGE)","AC View Clock"),
					739 -> new key("(0x280 + kbdm_CONSUM_PAGE)","AC Select Time Zone"),
					740 -> new key("(0x281 + kbdm_CONSUM_PAGE)","AC Edit Time Zones"),
					741 -> new key("(0x282 + kbdm_CONSUM_PAGE)","AC Set Alarm"),
					742 -> new key("(0x283 + kbdm_CONSUM_PAGE)","AC Clear Alarm"),
					743 -> new key("(0x284 + kbdm_CONSUM_PAGE)","AC Snooze Alarm"),
					744 -> new key("(0x285 + kbdm_CONSUM_PAGE)","AC Reset Alarm"),
					745 -> new key("(0x286 + kbdm_CONSUM_PAGE)","AC Synchronize"),
					746 -> new key("(0x287 + kbdm_CONSUM_PAGE)","AC Send/Receive"),
					747 -> new key("(0x288 + kbdm_CONSUM_PAGE)","AC Send To"),
					748 -> new key("(0x289 + kbdm_CONSUM_PAGE)","AC Reply"),
					749 -> new key("(0x28A + kbdm_CONSUM_PAGE)","AC Reply All"),
					750 -> new key("(0x28B + kbdm_CONSUM_PAGE)","AC Forward Msg"),
					751 -> new key("(0x28C + kbdm_CONSUM_PAGE)","AC Send"),
					752 -> new key("(0x28D + kbdm_CONSUM_PAGE)","AC Attach File"),
					753 -> new key("(0x28E + kbdm_CONSUM_PAGE)","AC Upload"),
					754 -> new key("(0x28F + kbdm_CONSUM_PAGE)","AC Download (Save Target As)"),
					755 -> new key("(0x290 + kbdm_CONSUM_PAGE)","AC Set Borders"),
					756 -> new key("(0x291 + kbdm_CONSUM_PAGE)","AC Insert Row"),
					757 -> new key("(0x292 + kbdm_CONSUM_PAGE)","AC Insert Column"),
					758 -> new key("(0x293 + kbdm_CONSUM_PAGE)","AC Insert File"),
					759 -> new key("(0x294 + kbdm_CONSUM_PAGE)","AC Insert Picture"),
					760 -> new key("(0x295 + kbdm_CONSUM_PAGE)","AC Insert Object"),
					761 -> new key("(0x296 + kbdm_CONSUM_PAGE)","AC Insert Symbol"),
					762 -> new key("(0x297 + kbdm_CONSUM_PAGE)","AC Save and Close"),
					763 -> new key("(0x298 + kbdm_CONSUM_PAGE)","AC Rename"),
					764 -> new key("(0x299 + kbdm_CONSUM_PAGE)","AC Merge"),
					765 -> new key("(0x29A + kbdm_CONSUM_PAGE)","AC Split"),
					766 -> new key("(0x29B + kbdm_CONSUM_PAGE)","AC Distribute Horizontally"),
					767 -> new key("(0x29C + kbdm_CONSUM_PAGE)","AC Distribute Vertically"),

					775 -> new key("(0x00E + kbdm_BUTTON_PAGE)","HID Button 14:  Preset,new KeyRef(4"),
					776 -> new key("(0x013 + kbdm_BUTTON_PAGE)","HID Button 19:  Webcam"),
					777 -> new key("(0x014 + kbdm_BUTTON_PAGE)","HID Button 20:  Status"),
					778 -> new key("(0x016 + kbdm_BUTTON_PAGE)","HID Button 22:  Burn"),
					779 -> new key("(0x018 + kbdm_BUTTON_PAGE)","HID Button 24MediaLife"),
					780 -> new key("(0x019 + kbdm_BUTTON_PAGE)","HID Button 25:  Preset 1"),
					781 -> new key("(0x01A + kbdm_BUTTON_PAGE)","HID Button 26:  Preset 2"),
					782 -> new key("(0x01B + kbdm_BUTTON_PAGE)","HID Button 27:  Preset 3"),
					783 -> new key("(0x01D + kbdm_BUTTON_PAGE)","HID Button 29:  Cruise Control -"),
					784 -> new key("(0x01E + kbdm_BUTTON_PAGE)","HID Button 30:  Cruise Control +"),
					785 -> new key("(0x025 + kbdm_BUTTON_PAGE)","HID Button 37:  Zoom Long -"),
					786 -> new key("(0x026 + kbdm_BUTTON_PAGE)","HID Button 38:  Zoom Long +"),
					787 -> new key("(0x026 + kbdm_BUTTON_PAGE)","HID Button 38:  Zoom Long +"),
					788 -> new key("(0x025 + kbdm_BUTTON_PAGE)","HID Button 45:  Fn key"),
					789 -> new key("(0x030 + kbdm_BUTTON_PAGE)","HID Button 48:  VoIP Dialler"),
					790 -> new key("(0x031 + kbdm_BUTTON_PAGE)","HID Button 49:  VoIP Call"),
					791 -> new key("(0x032 + kbdm_BUTTON_PAGE)","HID Button 50:  VoIP HangUp / Reject Call"),
					792 -> new key("(0x033 + kbdm_BUTTON_PAGE)","HID Button 51:  VoIP AutoAnswer"),
					793 -> new key("(0x034 + kbdm_BUTTON_PAGE)","HID Button 52:  VoIP SpeedDial1"),
					794 -> new key("(0x035 + kbdm_BUTTON_PAGE)","HID Button 53:  VoIP SpeedDial2"),
					795 -> new key("(0x036 + kbdm_BUTTON_PAGE)","HID Button 54:  VoIP SpeedDial3"),
					796 -> new key("(0x037 + kbdm_BUTTON_PAGE)","HID Button 55:  VoIP SpeedDial4"),
					797 -> new key("(0x038 + kbdm_BUTTON_PAGE)","HID Button 56:  Mic Mute"),
					798 -> new key("(0x039 + kbdm_BUTTON_PAGE)","HID Button 57:  Timer Event"),
					799 -> new key("(0x03A + kbdm_BUTTON_PAGE)","HID Button 58:  Timer Event End"),
					800 -> new key("(0x03B + kbdm_BUTTON_PAGE)","HID Button 59:  Alarm Event"),
					801 -> new key("(0x03C + kbdm_BUTTON_PAGE)","HID Button 60:  Alarm Event End"),
					802 -> new key("(0x03E + kbdm_BUTTON_PAGE)","HID Button 62:  Exposé"),
					803 -> new key("(0x041 + kbdm_BUTTON_PAGE)","HID Button 65:  Fn+F1"),
					804 -> new key("(0x042 + kbdm_BUTTON_PAGE)","HID Button 66:  Fn+F2"),
					805 -> new key("(0x043 + kbdm_BUTTON_PAGE)","HID Button 67:  Fn+F3"),
					806 -> new key("(0x044 + kbdm_BUTTON_PAGE)","HID Button 68:  Fn+F4"),
					807 -> new key("(0x045 + kbdm_BUTTON_PAGE)","HID Button 69:  Fn+F5"),
					808 -> new key("(0x046 + kbdm_BUTTON_PAGE)","HID Button 70:  Fn+F6"),
					809 -> new key("(0x047 + kbdm_BUTTON_PAGE)","HID Button 71:  Fn+F7"),
					810 -> new key("(0x048 + kbdm_BUTTON_PAGE)","HID Button 72:  Fn+F8"),
					811 -> new key("(0x049 + kbdm_BUTTON_PAGE)","HID Button 73:  Fn+F9"),
					812 -> new key("(0x04A + kbdm_BUTTON_PAGE)","HID Button 74:  Fn+F10"),
					813 -> new key("(0x04B + kbdm_BUTTON_PAGE)","HID Button 75:  Fn+F11"),
					814 -> new key("(0x04C + kbdm_BUTTON_PAGE)","HID Button 76:  Fn+F12"),
					815 -> new key("(0x04D + kbdm_BUTTON_PAGE)","HID Button 77:  Fn+PrintScreen"),
					816 -> new key("(0x04E + kbdm_BUTTON_PAGE)","HID Button 78:  Fn+InsertScroll"),
					817 -> new key("(0x04F + kbdm_BUTTON_PAGE)","HID Button 79:  Fn+PauseBreak"),
					818 -> new key("(0x055 + kbdm_BUTTON_PAGE)","HID Button 85:  Backlight -"),
					819 -> new key("(0x056 + kbdm_BUTTON_PAGE)","HID Button 86:  Backlight +"),
					820 -> new key("(0x057 + kbdm_BUTTON_PAGE)","HID Button 87:  Backlight Auto"),
					821 -> new key("(0x06C + kbdm_BUTTON_PAGE)","HID Button 108: NumPad /"),
					822 -> new key("(0x06D + kbdm_BUTTON_PAGE)","HID Button 109: NumPad *"),
					823 -> new key("(0x06E + kbdm_BUTTON_PAGE)","HID Button 110: NumPad -"),
					824 -> new key("(0x06F + kbdm_BUTTON_PAGE)","HID Button 111: NumPad +"),
					825 -> new key("(0x070 + kbdm_BUTTON_PAGE)","HID Button 112: NumPad 0"),
					826 -> new key("(0x071 + kbdm_BUTTON_PAGE)","HID Button 113: NumPad 1"),
					827 -> new key("(0x072 + kbdm_BUTTON_PAGE)","HID Button 114: NumPad 2"),
					828 -> new key("(0x073 + kbdm_BUTTON_PAGE)","HID Button 115: NumPad 3"),
					829 -> new key("(0x074 + kbdm_BUTTON_PAGE)","HID Button 116: NumPad,new KeyRef(4"),
					830 -> new key("(0x075 + kbdm_BUTTON_PAGE)","HID Button 117: NumPad,new KeyRef(5"),
					831 -> new key("(0x076 + kbdm_BUTTON_PAGE)","HID Button 118: NumPad,new KeyRef(6"),
					832 -> new key("(0x077 + kbdm_BUTTON_PAGE)","HID Button 119: NumPad,new KeyRef(7"),
					833 -> new key("(0x078 + kbdm_BUTTON_PAGE)","HID Button 120: NumPad,new KeyRef(8"),
					834 -> new key("(0x079 + kbdm_BUTTON_PAGE)","HID Button 121: NumPad 9"),
					835 -> new key("(0x07A + kbdm_BUTTON_PAGE)","HID Button 122: NumPad ."),
					836 -> new key("(0x07B + kbdm_BUTTON_PAGE)","HID Button 123: Disable NumLock OSD"),

					900 -> new key("(0x00D+ kbdm_MSMediaRemote_PAGE)","Green Start Button Navigation"),
					901 -> new key("(0x02B+ kbdm_MSMediaRemote_PAGE)","Closed Captioning AV Control Power"),
					902 -> new key("(0x05A+ kbdm_MSMediaRemote_PAGE)","TeleText On / Off TeleText "),
					903 -> new key("(0x05B+ kbdm_MSMediaRemote_PAGE)","TeleText Red TeleText "),
					904 -> new key("(0x05C+ kbdm_MSMediaRemote_PAGE)","TeleText Green TeleText "),
					905 -> new key("(0x05D+ kbdm_MSMediaRemote_PAGE)","TeleText Yellow TeleText "),
					906 -> new key("(0x05E+ kbdm_MSMediaRemote_PAGE)","TeleText Blue TeleText "),
					907 -> new key("(0x025+ kbdm_MSMediaRemote_PAGE)","Live TV Media Center "),
					908 -> new key("(0x047+ kbdm_MSMediaRemote_PAGE)","Music Media<br/>Center"),
					909 -> new key("(0x048+ kbdm_MSMediaRemote_PAGE)","Recorded TV Media Center "),
					910 -> new key("(0x049+ kbdm_MSMediaRemote_PAGE)","Pictures Media Center "),
					911 -> new key("(0x04A+ kbdm_MSMediaRemote_PAGE)","Videos Media Center "),
					912 -> new key("(0x050+ kbdm_MSMediaRemote_PAGE)","FM Radio Media Center "),
					913 -> new key("(0x03C+ kbdm_MSMediaRemote_PAGE)","OnSpot Media Center "),
					914 -> new key("(0x03D+ kbdm_MSMediaRemote_PAGE)","OnSpot App Media Center "),
					915 -> new key("(0x024+ kbdm_MSMediaRemote_PAGE)","DVD Menu DVD"),
					916 -> new key("(0x04B+ kbdm_MSMediaRemote_PAGE)","DVD Angle DVD"),
					917 -> new key("(0x04C+ kbdm_MSMediaRemote_PAGE)","DVD Audio DVD"),
					918 -> new key("(0x04D+ kbdm_MSMediaRemote_PAGE)","DVD Subtitle DVD"),
					919 -> new key("(0x028+ kbdm_MSMediaRemote_PAGE)","Eject DVD"),
					920 -> new key("(0x043+ kbdm_MSMediaRemote_PAGE)","DVD Top Menu DVD"),
					921 -> new key("(0x032+ kbdm_MSMediaRemote_PAGE)","Ext0 Extensibility"),
					922 -> new key("(0x033+ kbdm_MSMediaRemote_PAGE)","Ext1 Extensibility"),
					923 -> new key("(0x034+ kbdm_MSMediaRemote_PAGE)","Ext2 Extensibility"),
					924 -> new key("(0x035+ kbdm_MSMediaRemote_PAGE)","Ext3 Extensibility"),
					925 -> new key("(0x036+ kbdm_MSMediaRemote_PAGE)","Ext4 Extensibility"),
					926 -> new key("(0x037+ kbdm_MSMediaRemote_PAGE)","Ext5 Extensibility"),
					927 -> new key("(0x038+ kbdm_MSMediaRemote_PAGE)","Ext6 Extensibility"),
					928 -> new key("(0x039+ kbdm_MSMediaRemote_PAGE)","Ext7 Extensibility"),
					929 -> new key("(0x03A+ kbdm_MSMediaRemote_PAGE)","Ext8 Extensibility"),
					930 -> new key("(0x080+ kbdm_MSMediaRemote_PAGE)","Ext9 Extensibility"),
					931 -> new key("(0x081+ kbdm_MSMediaRemote_PAGE)","Ext10 Extensibility"),
					932 -> new key("(0x06F+ kbdm_MSMediaRemote_PAGE)","Ext11 Extensibility"),
					933 -> new key("(0x027+ kbdm_MSMediaRemote_PAGE)","Zoom Other "),

					1101 -> new key("(0x101 + kbdm_BUTTON_PAGE)","HID Button 257: AVR power on/off"),
					1102 -> new key("(0x102 + kbdm_BUTTON_PAGE)","HID Button 258: STB power on/off"),
					1103 -> new key("(0x103 + kbdm_BUTTON_PAGE)","HID Button 259: TV power on/off"),
					1104 -> new key("(0x104 + kbdm_BUTTON_PAGE)","HID Button 260: Menu Dialog"),
					1105 -> new key("(0x105 + kbdm_BUTTON_PAGE)","HID Button 261: Info Dialog"),
					1106 -> new key("(0x106 + kbdm_BUTTON_PAGE)","HID Button 262: List Dialog"),
					1107 -> new key("(0x107 + kbdm_BUTTON_PAGE)","HID Button 263: User Dialog"),
					1108 -> new key("(0x104 + kbdm_CONSUM_PAGE)","Media Player"),
					1109 -> new key("(0x001 + kbdm_GENERIC_PAGE)","Check Light"),
					1110 -> new key("(0x32B + kbdm_COMPOUND_PAGE)","Wake / Suspend"),
					1111 -> new key("(0x407 + kbdm_COMPOUND_PAGE)","Application Switch"),
					1112 -> new key("(0x410 + kbdm_COMPOUND_PAGE)","Show Desktop"),
					1113 -> new key("(0x510 + kbdm_COMPOUND_PAGE)","Minimize Window"),
					1114 -> new key("(0x408 + kbdm_COMPOUND_PAGE)","Restore Window"),
					1115 -> new key("(0x40F + kbdm_COMPOUND_PAGE)","My Computer"),
					1116 -> new key("(0x40F + kbdm_COMPOUND_PAGE)","Lock Computer"),
					1117 -> new key("(0x000 + kbdm_UNDEF_PAGE)","Battery Test"),
					1118 -> new key("(0x33D + kbdm_COMPOUND_PAGE)","Close Window"),
					1119 -> new key("(0x415 + kbdm_COMPOUND_PAGE)","Run App"),
					1120 -> new key("(0x000 + kbdm_UNDEF_PAGE)","BT connect"),
					1121 -> new key("(0x000 + kbdm_UNDEF_PAGE)","Language Switch"),
					1122 -> new key("(0x000 + kbdm_UNDEF_PAGE)","CtrlX"),
					1123 -> new key("(0x000 + kbdm_UNDEF_PAGE)","CtrlC"),
					1124 -> new key("(0x000 + kbdm_UNDEF_PAGE)","CtrlV"),
					1125 -> new key("(0x000 + kbdm_UNDEF_PAGE)","~NoFrow"),
					1126 -> new key("(0x000 + kbdm_UNDEF_PAGE)","`NoFrow")
					)
}