/* Generated By:JavaCC: Do not edit this line. BuildReleaseConstants.java */
public interface BuildReleaseConstants {

  int EOF = 0;
  int ALPHA_CHAR = 6;
  int NUM_CHAR = 7;
  int ALPHANUM_CHAR = 8;
  int IDENTIFIER_CHAR = 9;
  int IDENTIFIER = 10;
  int QUOTED_STRING_NB = 11;
  int QUOTED_STRING = 12;
  int WHITESPACE = 13;
  int NEWLINE = 14;
  int QUOTE = 15;
  int EOL = 16;
  int TAG_START = 17;
  int ENDTAG_START = 18;
  int COMMENT_START = 19;
  int DOCTYPE_START = 20;
  int DECL_START = 21;
  int CDATA_START = 22;
  int PCDATA = 23;
  int PCDATA_QS = 24;
  int PCDATA_Q = 25;
  int TAG_NAME = 27;
  int LST_ERROR = 28;
  int ATTR_NAME = 30;
  int TAG_END = 31;
  int TAG_SLASHEND = 32;
  int ATTR_EQ = 33;
  int LIT_ERROR = 34;
  int ATTR_VAL = 36;
  int LAV_ERROR = 37;
  int COMMENT_END = 38;
  int DASH = 39;
  int COMMENT_EOL = 40;
  int COMMENT_WORD = 41;
  int DOCTYPE_END = 42;
  int DECL_END = 43;
  int DOCTYPE_WORD = 44;
  int CDATA_END = 45;
  int CLOSING = 46;
  int CDATA_EOL = 47;
  int CDATA_WORD = 48;

  int DEFAULT = 0;
  int LexCdata = 1;
  int LexDocType = 2;
  int LexComment = 3;
  int LexAttrVal = 4;
  int LexInTag = 5;
  int LexStartTag = 6;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<QUOTED_STRING_NB>",
    "<QUOTED_STRING>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "\"\\\"\"",
    "<EOL>",
    "\"<\"",
    "\"</\"",
    "\"<!--\"",
    "\"<!\"",
    "\"<?\"",
    "\"<![CDATA[\"",
    "<PCDATA>",
    "<PCDATA_QS>",
    "<PCDATA_Q>",
    "<token of kind 26>",
    "<TAG_NAME>",
    "<LST_ERROR>",
    "<token of kind 29>",
    "<ATTR_NAME>",
    "\">\"",
    "\"/>\"",
    "\"=\"",
    "<LIT_ERROR>",
    "<token of kind 35>",
    "<ATTR_VAL>",
    "<LAV_ERROR>",
    "<COMMENT_END>",
    "\"-\"",
    "<COMMENT_EOL>",
    "<COMMENT_WORD>",
    "\">\"",
    "\"?>\"",
    "<DOCTYPE_WORD>",
    "\"]]>\"",
    "\"]\"",
    "<CDATA_EOL>",
    "<CDATA_WORD>",
  };

}
